'use strict';
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
if (!reduced && 'IntersectionObserver' in window) {
 document.body.classList.add('motion-enabled');
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});
 document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
}
document.querySelector('#year').textContent=new Date().getFullYear();
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
let scrollQueued=false;window.addEventListener('scroll',()=>{if(scrollQueued)return;scrollQueued=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=(max>0?scrollY/max*100:0)+'%';scrollQueued=false})},{passive:true});
const names=['WEDDING EDITS','BIRTHDAY VIDEO V1','BIRTHDAY VIDEO V2 / 3D','REELS + SUBTITLES','LYRICAL VIDEOS'];
document.querySelectorAll('.service').forEach(s=>s.addEventListener('toggle',()=>{if(!s.open)return;document.querySelectorAll('.service').forEach(other=>{if(other!==s)other.open=false});const index=Number(s.dataset.service);document.querySelector('.kinetic-number').textContent=String(index+1).padStart(2,'0');document.querySelector('#visual-name').textContent=names[index]}));
function safeUrl(raw){try{const url=new URL(raw,location.href);return ['https:','http:'].includes(url.protocol)?url:null}catch{return null}}
function embedUrl(raw){const url=safeUrl(raw);if(!url)return null;let id=null;if(['www.youtube.com','youtube.com','m.youtube.com'].includes(url.hostname))id=url.searchParams.get('v')||url.pathname.match(/^\/(?:shorts|embed)\/([\w-]{11})/)?.[1];if(url.hostname==='youtu.be')id=url.pathname.slice(1);if(id&&/^[\w-]{11}$/.test(id))return 'https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1';if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(url.hostname)){id=url.pathname.match(/(?:video\/)?(\d+)/)?.[1];if(id)return 'https://player.vimeo.com/video/'+id}return null}
let projects=[],filter='all';const grid=document.querySelector('#projects');
function render(){grid.replaceChildren();const matches=projects.filter(p=>filter==='all'||p.type===filter);if(!matches.length){const empty=document.createElement('div');empty.className='empty-state';const title=document.createElement('strong');title.textContent=filter==='video'?'New edits, coming into frame.':'More work is on the way.';const copy=document.createElement('span');copy.textContent=filter==='video'?'Published video edits will appear here. Explore the studio artwork in the meantime.':'Check back for the next story.';empty.append(title,copy);grid.append(empty);return}matches.forEach((p,i)=>{const button=document.createElement('button');button.className='project-card';button.setAttribute('aria-label','Open '+p.title);const visual=document.createElement('div');visual.className='project-image';const thumb=safeUrl(p.thumbnail);if(thumb){const img=document.createElement('img');img.src=thumb.href;img.alt=p.title;img.loading='lazy';img.width=900;img.height=720;img.addEventListener('error',()=>{img.remove();visual.classList.add('missing-thumbnail')});visual.append(img)}const label=document.createElement('span');label.className='art-label';label.textContent=p.type==='image'?'STUDIO ARTWORK':'VIDEO EDIT';const open=document.createElement('span');open.className='project-open';open.textContent=p.type==='image'?'+':'▶';open.setAttribute('aria-hidden','true');visual.append(label,open);const caption=document.createElement('div');caption.className='project-caption';const info=document.createElement('div');const title=document.createElement('h3');title.textContent=p.title;const cat=document.createElement('p');cat.textContent=p.category;info.append(title,cat);const index=document.createElement('span');index.textContent=String(i+1).padStart(2,'0');caption.append(info,index);button.append(visual,caption);button.addEventListener('click',()=>openProject(p));grid.append(button)})}
const dialog=document.querySelector('#viewer'),media=document.querySelector('#viewer-media');
function openProject(p){document.querySelector('#viewer-title').textContent=p.title;document.querySelector('#viewer-category').textContent=p.category;document.querySelector('#viewer-description').textContent=p.description||'';media.replaceChildren();const external=document.querySelector('#viewer-external');external.hidden=true;const url=safeUrl(p.media);if(!url){media.textContent='This project link is unavailable.'}else if(p.type==='image'){const img=document.createElement('img');img.src=url.href;img.alt=p.title;media.append(img)}else{const embed=embedUrl(p.media);if(embed){const iframe=document.createElement('iframe');iframe.src=embed;iframe.title=p.title;iframe.allow='autoplay; fullscreen; picture-in-picture';iframe.allowFullscreen=true;media.append(iframe)}else if(/\.(mp4|webm|mov)(?:$|\?)/i.test(url.href)){const video=document.createElement('video');video.src=url.href;video.controls=true;video.playsInline=true;video.preload='metadata';media.append(video)}else{const note=document.createElement('p');note.textContent='Watch this edit on its original platform.';media.append(note)}external.href=url.href;external.hidden=false}dialog.showModal();document.body.style.overflow='hidden'}
function close(){dialog.close()}document.querySelector('#close-viewer').addEventListener('click',close);dialog.addEventListener('close',()=>{media.replaceChildren();document.body.style.overflow=''});dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)close()}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(other=>{other.classList.toggle('active',other===b);other.setAttribute('aria-pressed',String(other===b))});render()}));
fetch('portfolio.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Portfolio unavailable');return r.json()}).then(data=>{if(!Array.isArray(data.projects))throw new Error('Invalid portfolio');projects=data.projects.filter(p=>p&&typeof p.title==='string'&&['image','video'].includes(p.type));render()}).catch(()=>{document.querySelector('#work-error').hidden=false});
