'use strict';
const OWNER='salmanfaris1234',REPO='portfolio',BRANCH='sf-visual-lab';
const API='https://api.github.com',root=API+'/repos/'+OWNER+'/'+REPO;
let token='',projects=[],fileSha='',editingId=null,dirty=false,busy=false,removeId=null;
const pendingFiles=new Map(),$=s=>document.querySelector(s);
function status(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error)}
function encode(text){return btoa(Array.from(new TextEncoder().encode(text),b=>String.fromCharCode(b)).join(''))}
function decode(content){return new TextDecoder().decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0)))}
async function api(path,method='GET',body){const response=await fetch(API+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok){let message='';try{message=(await response.json()).message||''}catch{}if(response.status===409)throw new Error('The portfolio changed on GitHub. Copy any unsaved text, reconnect to load the latest version, then reapply your changes.');if(response.status===401)throw new Error('The token is invalid or expired. Please reconnect.');if(response.status===403)throw new Error('GitHub denied this request. Check the token’s repository access and Contents permission.');throw new Error('GitHub request failed ('+response.status+'). '+message)}return response.status===204?null:response.json()}
$('#connect-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;token=$('#token').value.trim();status('Checking your GitHub account…');try{const user=await api('/user');if(user.login.toLowerCase()!==OWNER)throw new Error('Only the salmanfaris1234 owner account can publish here.');const file=await api('/repos/'+OWNER+'/'+REPO+'/contents/portfolio.json?ref='+BRANCH);const data=JSON.parse(decode(file.content));if(!Array.isArray(data.projects))throw new Error('The portfolio file has an unexpected format.');projects=data.projects;fileSha=file.sha;pendingFiles.clear();dirty=false;editingId=null;$('#token').value='';$('#auth').hidden=true;$('#editor').hidden=false;$('#project-form').reset();render();status('Connected. Add a project or select an existing edit.')}catch(err){token='';status(err.message,true)}finally{button.disabled=false}});
function validUrl(raw){try{const url=new URL(raw,location.href);return ['https:','http:'].includes(url.protocol)}catch{return false}}
function setDirty(value){dirty=value;$('#draft-state').textContent=value?'Unpublished changes':'No unpublished changes';$('#publish').disabled=!value||busy}
function render(){const list=$('#project-list');list.replaceChildren();if(!projects.length){const empty=document.createElement('p');empty.textContent='Your portfolio is ready for its first edit.';list.append(empty)}projects.forEach((p,i)=>{const card=document.createElement('div');card.className='draft-card';const h=document.createElement('h3');h.textContent=p.title;const meta=document.createElement('p');meta.textContent=p.category+' · '+(p.type==='video'?'Video':'Artwork');const actions=document.createElement('div');actions.className='draft-actions';[['Edit',()=>edit(p)],['Up',()=>move(i,-1)],['Down',()=>move(i,1)],['Remove',()=>{removeId=p.id;$('#remove-dialog').showModal()}]].forEach(([label,handler])=>{const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=label;b.disabled=busy||(label==='Up'&&i===0)||(label==='Down'&&i===projects.length-1);b.addEventListener('click',handler);actions.append(b)});card.append(h,meta,actions);list.append(card)});setDirty(dirty)}
function move(i,delta){if(busy)return;const dest=i+delta;if(dest<0||dest>=projects.length)return;[projects[i],projects[dest]]=[projects[dest],projects[i]];setDirty(true);render()}
function clear(){editingId=null;$('#project-form').reset();$('#form-title').textContent='New project';$('#thumb-preview').hidden=true;$('#thumb-preview').removeAttribute('src')}
function edit(p){if(busy)return;clear();editingId=p.id;$('#form-title').textContent='Edit project';['title','category','type','media','thumbnail','description'].forEach(key=>$('#'+key).value=p[key]||'');if(p.thumbnail&&validUrl(p.thumbnail)){$('#thumb-preview').src=p.thumbnail;$('#thumb-preview').hidden=false}$('#title').focus()}
$('#new-project').addEventListener('click',()=>{clear();$('#title').focus()});$('#cancel-edit').addEventListener('click',clear);
let previewUrl=null;$('#thumb-file').addEventListener('change',()=>{const file=$('#thumb-file').files[0];if(previewUrl)URL.revokeObjectURL(previewUrl);if(file){previewUrl=URL.createObjectURL(file);$('#thumb-preview').src=previewUrl;$('#thumb-preview').hidden=false}else{$('#thumb-preview').hidden=true}});
$('#project-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;let thumbnail=$('#thumbnail').value.trim();const media=$('#media').value.trim();if(!validUrl(media)|| (thumbnail&&!validUrl(thumbnail))){status('Use a valid video link and thumbnail image link.',true);return}const file=$('#thumb-file').files[0];const id=editingId||crypto.randomUUID();if(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>4*1024*1024){status('Choose a JPG, PNG, or WebP image under 4 MB.',true);return}const extension={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];const name='assets/uploads/'+id+'-'+Date.now()+'.'+extension;const data=await file.arrayBuffer();pendingFiles.set(name,btoa(Array.from(new Uint8Array(data),b=>String.fromCharCode(b)).join('')));thumbnail=name}if(!thumbnail&&$('#type').value==='image')thumbnail=media;if(!thumbnail){status('Add a thumbnail image link or upload a thumbnail for your video.',true);return}const project={id,title:$('#title').value.trim(),category:$('#category').value,type:$('#type').value,media,thumbnail,description:$('#description').value.trim()};if(!project.title){status('Enter a project title.',true);return}const index=projects.findIndex(p=>p.id===id);if(index<0)projects.unshift(project);else projects[index]=project;setDirty(true);render();clear();status('Saved to your draft. Publish when you’re ready.')});
$('#keep-project').addEventListener('click',()=>$('#remove-dialog').close());$('#confirm-remove').addEventListener('click',()=>{projects=projects.filter(p=>p.id!==removeId);if(editingId===removeId)clear();setDirty(true);render();$('#remove-dialog').close();status('Removed from draft. Publish to update the live portfolio.')});
function lock(value){busy=value;$('#project-form').querySelectorAll('input,button,select,textarea').forEach(el=>el.disabled=value);$('#new-project').disabled=value;$('#disconnect').disabled=value;render()}
$('#publish').addEventListener('click',async()=>{if(!dirty||busy)return;lock(true);status('Publishing your portfolio…');try{const latest=await api('/repos/'+OWNER+'/'+REPO+'/contents/portfolio.json?ref='+BRANCH);if(latest.sha!==fileSha)throw new Error('Your portfolio changed on GitHub. Copy unsaved text and reconnect before publishing.');const used=new Set(projects.map(p=>p.thumbnail));for(const [path,content] of pendingFiles){if(!used.has(path))continue;await api('/repos/'+OWNER+'/'+REPO+'/contents/'+path,'PUT',{message:'Add SF portfolio thumbnail',content,branch:BRANCH});pendingFiles.delete(path)}const result=await api('/repos/'+OWNER+'/'+REPO+'/contents/portfolio.json','PUT',{message:'Update SF Visual Lab portfolio',content:encode(JSON.stringify({projects},null,2)+'\n'),sha:fileSha,branch:BRANCH});fileSha=result.content.sha;setDirty(false);status('Saved to GitHub. The public site will update once GitHub Pages finishes deploying.')}catch(err){status(err.message,true)}finally{lock(false)}});
$('#disconnect').addEventListener('click',()=>{if(dirty&&!confirm('Disconnect and discard unpublished changes?'))return;token='';projects=[];fileSha='';pendingFiles.clear();dirty=false;clear();$('#editor').hidden=true;$('#auth').hidden=false;status('Disconnected.')});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
